"""evolution table

Revision ID: 2ef072e2ad0d
Revises: 637353110986
Create Date: 2023-12-13 00:02:12.002156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef072e2ad0d'
down_revision: Union[str, None] = '637353110986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processingevolutionrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_initiator', sa.Integer(), nullable=False),
    sa.Column('image1', sa.Text(), nullable=True),
    sa.Column('image2', sa.Text(), nullable=True),
    sa.Column('process_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.Column('image_base64', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processingevolutionrequest')
    # ### end Alembic commands ###
