"""persist feature matrix

Revision ID: 3f2eda349ee4
Revises: 2ef072e2ad0d
Create Date: 2023-12-14 04:04:39.147655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f2eda349ee4'
down_revision: Union[str, None] = '2ef072e2ad0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processingrequest', sa.Column('matrix', sa.JSON(), nullable=True))
    op.drop_column('processingrequest', 'imagepath')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processingrequest', sa.Column('imagepath', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('processingrequest', 'matrix')
    # ### end Alembic commands ###
